### ISSUE TITLE
Security issue: Cryptography.PoorEntropy on SSLSessionContextImpl

### ISSUE THREAD

**Issue by GabrieleBarboni** [ibmruntimes/openj9-openjdk-jdk21#182]
Our product security scan has found a security issue related to  Cryptography.PoorEntropy (https://cwe.mitre.org/data/definitions/331) related to the usage of Random instead of SecureRandom in SSLSessionContextImpl.java.
Stack trace:
java.util.Random.next(Random.java:445)
java.util.Random.nextInt(Random.java:495)
sun.security.ssl.SSLSessionContextImpl.<init>(SSLSessionContextImpl.java:96)
sun.security.ssl.SSLContextImpl.<init>(SSLContextImpl.java:78)
sun.security.ssl.SSLContextImpl$CustomizedTLSContext.<init>(SSLContextImpl.java:851)
sun.security.ssl.SSLContextImpl$TLSContext.<init>(SSLContextImpl.java:883)
java.security.Provider$Service.newInstanceOf(Provider.java:1950)
java.security.Provider$Service.newInstanceUtil(Provider.java:1957)
java.security.Provider$Service.newInstance(Provider.java:1932)
sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
javax.net.ssl.SSLContext.getInstance(SSLContext.java:185)

Is it possible to switch to SecureRandom?

**Comment by pshipton** [comment]
@jasonkatonica can someone pls take a look to answer the question.

**Comment by jasonkatonica** [comment]
In the [latest version of the SSLSessionContextImpl code](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/2e0da11d023e701e86f58fd2ee328a534716077b/src/java.base/share/classes/sun/security/ssl/SSLSessionContextImpl.java#L96) I can see that this random number being generated is being used as a session identifier for TLS handshakes. Given that this is a not a cryptographic use of a random number, but is instead just being used to generate an identifier, the use of a Random class instead of a true `SecureRandom` class does seem reasonable to me. There is also a comment in the code with similar thoughts.

**Comment by GabrieleBarboni** [comment]
Thanks for your answer. Closing based on your answer.
